### ISSUE TITLE
Library definition gives warnings

### ISSUE THREAD

**Issue by sanfair** [archual/drupal_materialize_theme#2]
warning: Couldn't find constant  CSS_FONTS and CSS_MODULES
explanation: *.libraries.yml contains labels "fonts" and "modules" witch are not suported. 

"modules" can be replace with "component" or  you can find better solution =)

Please change or remove this label from /THEME_ROOT/materialize.libraries.yml

**Comment by archual** [comment]
Hi, Sanfair.
This project was be moved to Drupal.org repository and has a lot of changes. 
Please see here: [https://www.drupal.org/project/materialize](https://www.drupal.org/project/materialize)
I will close this repository shortly.
